vich_uploader:
    db_driver: orm

    mappings:
        perfil_imagem:
            uri_prefix: /uploads/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/profiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer